select * from customer limit 10


-- What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Total_Revenue
from customer
group by gender


-- Which customers used a discount but still spent more than the average purchase amount?

select customer_id,item_purchased,purchase_amount,discount_applied 
from customer
where purchase_amount >= (select round(avg(purchase_amount),2) as avg_purchase_amount from customer) and
discount_applied = 'Yes'


-- Which are the top 5 products with the highest average review rating?


WITH top_5 AS (
    SELECT 
        item_purchased AS products,
        ROUND(AVG(review_rating)::numeric, 2) AS avg_rating,
        RANK() OVER(ORDER BY AVG(review_rating) DESC) AS rnk
    FROM customer
    GROUP BY item_purchased
)

SELECT *
FROM top_5
WHERE rnk <= 5;


-- Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type , round(avg(purchase_amount),2) as avg_purch_amount
from customer
group by shipping_type
-- having shipping_type = 'Express' or shipping_type = 'Standard'
having shipping_type in ('Express','Standard')



-- Do subscribed customers spend more? Compare average spend 
-- and total revenue between subscribers and non-subscribers.


select subscription_status, 
count(distinct customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spending,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue desc


-- Which 5 products have the highest percentage of purchases with discounts applied?

with Top_5 as (
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1  end)*100.0/ count(*),2) as discount_rate,

dense_rank() over(order by sum(case when discount_applied = 'Yes' then 1 end)*100.0/ count(*)   desc) as rnk
from customer
group by item_purchased


)

select item_purchased,discount_rate from Top_5
where rnk <=5


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select 
case when previous_purchases = 1 then 'New'
when previous_purchases >10 then 'Loyal'
else 'Returning' end as Segment_customers,
count(*)
from customer
group by case when previous_purchases = 1 then 'New'
when previous_purchases >10 then 'Loyal'
else 'Returning' end


-- What are the top 3 most purchased products within each category?

with top_3 as (
select category,item_purchased,count(*) as total_orders,
dense_rank() over(partition by category order by count(*) desc) as rnk
from customer
group by category,item_purchased

)
select * from top_3
where rnk<=3


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, 
count(customer_id) as repeat_customer

from customer
where previous_purchases >5 
group by subscription_status


-- What is the revenue contribution of each age group?

select age_group, round(sum(purchase_amount)*100.0/(select sum(purchase_amount) from customer),2) as contribution_in_revenue
from customer
group by age_group
order by sum(purchase_amount)*100.0/(select sum(purchase_amount) from customer) desc